name: muscles_builder
description: "Game for entertainment"
publish_to: 'none'

version: 1.0.4+16

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flame: ^1.30.1
  flame_audio: ^2.11.8
  shared_preferences: ^2.5.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  package_info_plus: ^8.3.0
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/gifs/
    - assets/icons/
    - assets/audio/
    - assets/images/
    - assets/images/viruses/virus_low/
    - assets/images/viruses/virus_medium/
    - assets/images/viruses/virus_high/
    - assets/images/viruses/virus_extreme/
  fonts:
    - family: Bungee-Regular
      fonts:
        - asset: assets/google_fonts/Bungee-Regular.ttf