name: muscles_builder
description: "Game for entertainment"
publish_to: 'none'

version: 1.0.1+9

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.30.1
  flame_audio: ^2.11.8
  shared_preferences: ^2.5.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  package_info_plus: ^8.3.0
  google_mobile_ads: ^6.0.0
  firebase_core: ^4.0.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/gifs/
    - assets/icons/
  fonts:
    - family: Bungee-Regular
      fonts:
        - asset: assets/google_fonts/Bungee-Regular.ttf