name: muscles_builder
description: "Game for entertainment"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.21.0
  flame_audio: ^2.10.5
  shared_preferences: ^2.3.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  package_info_plus: ^8.1.1
  google_mobile_ads: ^5.2.0
  firebase_core: ^3.9.0
  get_it: ^8.0.3
  image_picker: ^1.1.2

  domain:
    path: packages/domain

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/gifs/
    - assets/icons/
  fonts:
    - family: PressStart2P-Regular
      fonts:
        - asset: assets/google_fonts/PressStart2P-Regular.ttf